# Generated by Django 5.0.6 on 2026-06-10 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0001_initial'),
        ('servicios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='cliente',
            field=models.ForeignKey(limit_choices_to={'rol': 'cliente'}, on_delete=django.db.models.deletion.PROTECT, related_name='citas', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='cita',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='servicios.servicio', verbose_name='Servicio'),
        ),
        migrations.AddField(
            model_name='pago',
            name='cita',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pago', to='citas.cita', verbose_name='Cita'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='cliente',
            field=models.ForeignKey(limit_choices_to={'rol': 'cliente'}, on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='cita',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='citas.vehiculo', verbose_name='Vehículo'),
        ),
    ]
