# Generated by Django 5.0.6 on 2026-06-16 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_initial'),
        ('servicios', '0003_remove_promocion_servicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='servicio',
        ),
        migrations.AddField(
            model_name='cita',
            name='paquete',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='servicios.paquete', verbose_name='Paquete'),
            preserve_default=False,
        ),
    ]
