# Generated by Django 5.0.6 on 2026-06-17 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_remove_cita_servicio_cita_paquete'),
        ('servicios', '0003_remove_promocion_servicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='paquete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='servicios.paquete', verbose_name='Paquete'),
        ),
    ]
