# Generated by Django 5.0.6 on 2026-06-10 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio (MXN)')),
                ('duracion_horas', models.DecimalField(decimal_places=1, help_text='Tiempo estimado del servicio en horas', max_digits=4, verbose_name='Duración (horas)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='servicios/', verbose_name='Imagen')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='Descripción de la promo')),
                ('descuento_pct', models.DecimalField(decimal_places=2, help_text='Porcentaje de descuento (ej: 15 para 15%)', max_digits=5, verbose_name='Descuento (%)')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de fin')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promociones', to='servicios.servicio', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
