# Generated by Django 5.0.6 on 2026-06-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='nombre',
            field=models.CharField(default='Promoción General', help_text='Ej: Paquete Lluvia, Combo Verano', max_length=100, verbose_name='Nombre de la promoción'),
            preserve_default=False,
        ),
    ]
