# Generated by Django 5.0.6 on 2026-06-15 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_promocion_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocion',
            name='servicio',
        ),
        migrations.AlterField(
            model_name='promocion',
            name='descuento_pct',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Descuento (%)'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre de la promoción'),
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Paquete')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción de lo que incluye')),
                ('es_personalizado', models.BooleanField(default=False, verbose_name='¿Es personalizado por el cliente?')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('servicios', models.ManyToManyField(to='servicios.servicio', verbose_name='Servicios Incluidos')),
            ],
            options={
                'verbose_name': 'Paquete',
                'verbose_name_plural': 'Paquetes',
            },
        ),
        migrations.AddField(
            model_name='promocion',
            name='paquete',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='promociones', to='servicios.paquete', verbose_name='Paquete Asociado'),
            preserve_default=False,
        ),
    ]
