# Generated by Django 5.0.6 on 2026-06-10 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_actual', models.CharField(choices=[('recibido', 'Vehículo recibido'), ('en_lavado', 'En lavado'), ('en_pulido', 'En pulido/encerado'), ('en_detalles', 'En detalles finales'), ('listo', 'Listo para entrega'), ('entregado', 'Entregado al cliente')], default='recibido', max_length=20, verbose_name='Estado del servicio')),
                ('notas', models.TextField(blank=True, verbose_name='Notas del técnico')),
                ('foto_antes', models.ImageField(blank=True, null=True, upload_to='seguimiento/antes/', verbose_name='Foto antes')),
                ('foto_despues', models.ImageField(blank=True, null=True, upload_to='seguimiento/despues/', verbose_name='Foto después')),
                ('iniciado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Seguimiento',
                'verbose_name_plural': 'Seguimientos',
                'ordering': ['-actualizado_en'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cita_confirmada', 'Cita confirmada'), ('cita_cancelada', 'Cita cancelada'), ('servicio_iniciado', 'Servicio iniciado'), ('servicio_listo', 'Vehículo listo'), ('recordatorio', 'Recordatorio de cita'), ('general', 'Notificación general')], default='general', max_length=25, verbose_name='Tipo')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('leida', models.BooleanField(default=False, verbose_name='Leída')),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='citas.cita', verbose_name='Cita relacionada')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-creada_en'],
            },
        ),
    ]
