# Generated by Django 5.0.6 on 2026-06-10 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0002_initial'),
        ('seguimiento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Destinatario'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='cita',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='seguimiento', to='citas.cita', verbose_name='Cita'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='tecnico',
            field=models.ForeignKey(limit_choices_to={'rol': 'tecnico'}, on_delete=django.db.models.deletion.PROTECT, related_name='seguimientos', to=settings.AUTH_USER_MODEL, verbose_name='Técnico asignado'),
        ),
    ]
