# Generated by Django 5.0.6 on 2026-06-12 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='seguimiento',
            old_name='iniciado_en',
            new_name='creado_en',
        ),
        migrations.RenameField(
            model_name='seguimiento',
            old_name='notas',
            new_name='notas_tecnico',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='seguimiento',
            name='estado_actual',
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='estado',
            field=models.CharField(choices=[('recibido', 'Vehículo recibido'), ('en_lavado', 'En lavado'), ('en_pulido', 'En pulido/encerado'), ('en_detalles', 'En detalles finales'), ('listo', 'Listo para entrega'), ('entregado', 'Entregado al cliente')], default='recibido', max_length=15, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='notas_iniciales',
            field=models.TextField(blank=True, verbose_name='Notas iniciales'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('cita_confirmada', 'Cita confirmada'), ('cita_cancelada', 'Cita cancelada'), ('servicio_iniciado', 'Servicio iniciado'), ('servicio_listo', 'Servicio listo')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='foto_antes',
            field=models.ImageField(blank=True, null=True, upload_to='seguimiento/antes/', verbose_name='Foto antes del servicio'),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='foto_despues',
            field=models.ImageField(blank=True, null=True, upload_to='seguimiento/despues/', verbose_name='Foto después del servicio'),
        ),
    ]
