# Generated by Django 5.0.6 on 2026-06-16 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0003_rename_iniciado_en_seguimiento_creado_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='estado',
            field=models.CharField(choices=[('en_espera', 'En espera'), ('recibido', 'Vehículo recibido'), ('en_detalles', 'En detalles'), ('listo', 'Listo para entrega'), ('entregado', 'Entregado al cliente')], default='en_espera', max_length=15, verbose_name='Estado'),
        ),
    ]
