# Generated by Django 5.0.6 on 2026-06-11 23:37

import apps.usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=apps.usuarios.models.usuario_foto_path, verbose_name='Foto de perfil'),
        ),
    ]
